### ISSUE TITLE
How do I cite an I-D?

### ISSUE THREAD

**Issue by edmonds** [miekg/mmark#107]
Hi,

Is it possible to cite an I-D using mmark? I want to cite https://tools.ietf.org/html/draft-ietf-dnsop-refuse-any, so I put `[@?I-D.draft-ietf-dnsop-no-response-issue]` in my document, like https://github.com/miekg/mmark/wiki/Syntax#citations suggests. The XML that mmark produced caused xml2rfc to fail with:

```
Traceback (most recent call last):
  File "/usr/bin/xml2rfc", line 9, in <module>
    load_entry_point('xml2rfc==2.5.1', 'console_scripts', 'xml2rfc')()
  File "/usr/lib/python2.7/dist-packages/xml2rfc/run.py", line 151, in main
    xmlrfc = parser.parse()
  File "/usr/lib/python2.7/dist-packages/xml2rfc/parser.py", line 497, in parse
    include=True, line_no=getattr(element, 'sourceline', 0))
  File "/usr/lib/python2.7/dist-packages/xml2rfc/parser.py", line 222, in getReferenceRequest
    result = self.cache(path)
  File "/usr/lib/python2.7/dist-packages/xml2rfc/parser.py", line 344, in cache
    r = session.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'xml.resource.org' doesn't match either of '*.ietf.org', 'ietf.org'
```

I am kind of confused by that since there aren't any `xml.resource.org` URLs in the XML file that mmark generates.

Thanks!

**Comment by miekg** [comment]
Seems they moved (or are not updating the draft index correctly). Also: TLS error??

~~~
% echo '[@?I-D.draft-ietf-dnsop-no-response-issue]' | ./mmark/mmark -xml2 -page

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rfc SYSTEM 'rfc2629.dtd' []>
<t><xref target="I-D.draft-ietf-dnsop-no-response-issue"/>
</t>
<back>
<references title="Informative References">
<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-ietf-dnsop-no-response-issue.xml"?>
</references>

</back>
~~~
That link also doesn't exists.

Do you know if the repo for drafts was moved? The 
~~~
 -bib-id string
    	ID bibliography URL (default "https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/")
~~~
Might help here.

**Comment by edmonds** [comment]
Ah, interesting!

There isn't a http://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-ietf-dnsop-no-response-issue.xml resource (it 404's). The only resources that exist are the ones with explicit -00, -01, …, -08 versions. So that generates this, like you showed:

```
$ echo '[@?I-D.draft-ietf-dnsop-no-response-issue]' | mmark -xml2 -page 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rfc SYSTEM 'rfc2629.dtd' []>
<t><xref target="I-D.draft-ietf-dnsop-no-response-issue"/>
</t>
<back>
<references title="Informative References">
<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-ietf-dnsop-no-response-issue.xml"?>
</references>

</back>
```

So I added an explicit version and got this:

```
$ echo '[@?I-D.draft-ietf-dnsop-no-response-issue#08]' | mmark -xml2 -page
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rfc SYSTEM 'rfc2629.dtd' []>
<t><xref target="I-D.draft-ietf-dnsop-no-response-issue"/>
</t>
<back>
<references title="Informative References">
<?rfc include="https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.draft-draft-ietf-dnsop-no-response-issue-08.xml"?>
</references>

</back>
```

Note the URL has become `…/reference.I-D.draft-draft-ietf-dnsop-no-response-issue-08.xml` with `draft-` repeated. That doesn't exist either.

If I write it as `[@?I-D.ietf-dnsop-no-response-issue#08]` without the `draft-` then I get a successful document build. But I think that is a workaround for a bug in mmark? (This is the version in Debian sid, haven't tried `master`.)

I am not sure what xml2rfc is doing to get a TLS error. Maybe it's falling back to a bad URL or something? Haven't dug into it, but I guess there is a bug in xml2rfc too.

**Comment by edmonds** [comment]
Oh, now I see that there is a https://xml2rfc.tools.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-dnsop-no-response-issue.xml resource, without the `draft-` and without the version number. So I do need to write the citation as `[@?I-D.ietf-dnsop-no-response-issue]`. OK, this is not confusing at all.

**Comment by edmonds** [comment]
It looks like the xml2rfc bug was fixed in trunk but the fix hasn't been released yet :-\

```diff
From 5c7e2c13883504ab56f39eda4e745e5d7be0b1c3 Mon Sep 17 00:00:00 2001
From: "henrik@levkowetz.com"
 <henrik@levkowetz.com@420659e1-3e8f-4aa3-bc54-b4abac0350f5>
Date: Thu, 20 Oct 2016 11:43:13 +0000
Subject: [PATCH] Remove all references to xml.resource.org; it is not useful
 for fallback purposes any more.

git-svn-id: https://svn.tools.ietf.org/svn/tools/xml2rfc@2268 420659e1-3e8f-4aa3-bc54-b4abac0350f5
---
 trunk/cli/xml2rfc/parser.py | 4 +---
 1 file changed, 1 insertion(+), 3 deletions(-)

diff --git a/trunk/cli/xml2rfc/parser.py b/trunk/cli/xml2rfc/parser.py
index e9f9e733..457012b5 100644
--- a/trunk/cli/xml2rfc/parser.py
+++ b/trunk/cli/xml2rfc/parser.py
@@ -47,7 +47,6 @@ class CachingResolver(lxml.etree.Resolver):
                  no_network=False, network_locs= [
                      'http://xml2rfc.ietf.org/public/rfc/',
                      'http://xml2rfc.tools.ietf.org/public/rfc/',
-                     'http://xml.resource.org/public/rfc/',
                  ],
                  rfc_number=None):
         self.verbose = verbose
@@ -168,7 +167,7 @@ class CachingResolver(lxml.etree.Resolver):
               ['/usr/share/xml2rfc'].  On the GUI this can be configured
               manually but has the same initial defaults.
             - NETWORK refers to the online citation library.  On the CLI this
-              is http://xml.resource.org/public/rfc/.  On the GUI this 
+              is http://xml2rfc.ietf.org/public/rfc/.  On the GUI this 
               can be configured manually but has the same initial default.
 
             The caches in read_dirs are consulted in sequence order to find the
@@ -366,7 +365,6 @@ class XmlRfcParser:
                  no_network=False, network_locs=[
                      'http://xml2rfc.ietf.org/public/rfc/',
                      'http://xml2rfc.tools.ietf.org/public/rfc/',
-                     'http://xml.resource.org/public/rfc/',
                  ]
                  ):
         self.verbose = verbose
-- 
2.11.0
```

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] How do I cite an ..." ]
>It looks like the xml2rfc bug was fixed in trunk but the fix hasn't been released yet :-\

Is there something to do for mmark here? Improved docs?

**Comment by edmonds** [comment]
This paragraph in the documentation is a little unclear:

> For I-Ds you may want to add a draft sequence number, which can be done as such: [@?I-D.blah#06]. If you reference an I-D without a sequence number it will create a reference to the last I-D in citation index.

`blah` apparently needs to start with `draft-` if a sequence number is used, but must not start with `draft-` if the sequence number is omitted. IIUC?

Or maybe there's a way to make it "hard to misuse"? Perhaps avoid prepending `draft-` if `blah` already starts with `draft-`?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/mmark] How do I cite an ..." ]
>This paragraph in the documentation is a little unclear:
>
>> For I-Ds you may want to add a draft sequence number, which can be done as such: [@?I-D.blah#06]. If you reference an I-D without a sequence number it will create a reference to the last I-D in citation index.
>
>`blah` apparently needs to start with `draft-` if a sequence number is used, but must not start with `draft-` if the sequence number is omitted. IIUC?
>
>Or maybe there's a way to make it "hard to misuse"? Perhaps avoid prepending `draft-` if `blah` already starts with `draft-`?

Ah, indeed. Should add some tests for this. Think the rational behind it was how
the IETF stores and names these drafts. Being smarter does help yes.
